### PR TITLE
Introduce the 'discovery' resource

### PR DESCRIPTION
**Pull request by martinb3**
Please see the README for an explanation of the discovery resource. It is intended to provide a point of indirection on top of Chef search that we use today. We could later change out the backend to be consul, etcd, or even just node attributes or DNS.

### CODE REVIEW

**Comment by prometheanfire** [comment]
I think I understand, but had to read the library to do so.  I think simply stating what needle and haystack resolve down to when searching would help.

**Comment by martinb3** [comment]
@prometheanfire I did attempt to simply state it, in the README:

``````
+Provides a rudimentary discovery mechanism on top of chef search. For the
+purposes of this mechanism, we assume there are two string-typed keys. One key
+is considered the haystack, one the needle. The `discovery` resource and provider
+provides generic actions for marking any Chef node as a particular haystack and
+needle, as well as enumerating other Chef nodes in the same haystack, or finding
+the node corresponding to a particular needle within a particular haystack.
+
+The default implementation uses tags for storing this data, of the form
+`haystack` and `haystack_needle`. It uses the resource name for the haystack,
+and requires a needle is also provided.```
``````

**Comment by prometheanfire** [comment]
I was complaining that it still took me looking at the source :P

**Comment by jujugrrr** [comment]
Hi @martinb3 , thanks for it, we need something like this :wink: .

I agree with @prometheanfire on this one, I'm lost with those haystack and needles even after looking at the README :stuck_out_tongue_winking_eye: . I had to look at the code too, and it seems to simply  be tags with `haystack_needle`.

It seems we cannot really use other criteria like environment, or we would need something like :
`needle 'master AND chef_environment:#{node.chef_environment}'`.

I'd say this Resource is too much of abstraction/logic. It's not really a search_helper, it's more of a tagging/search "engine" ;-).

On a more technical point of view, I think Resources in this context are not the best tools, as we want to do a search and get a list of node/IP. We need a function rather than a procedure.

For me the helper should look a lot more simple than :

```
discovery 'mysql' do
  needle 'master'
  action :search
  data do |node|
    node_ip = best_ip_for(node)
    Chef::Log.info("#{node.name} was found as a mysql master at #{node_ip}")
  end
end
```

By example

```
node_ip = best_ip_for(discover('mysql','master'))
```

And to be honest, I'd rather not use Chef to get data/attributes from a search. A search for me should just return an IP/FQDN so it could be as simple as: 

```
node_ip_fqdn = discover('mysql','master')
```

ps : I think it's better if we don't automatically fail on Chef::Solo. Otherwise it can be hard to test with ChefSpec (if we use the Solo provider). I've prefer to avoid to have to add a guard in my recipe.

**Comment by martinb3** [comment]
My goal here was to provide something abstract. I was hesitant to call it 'search with tags' or say that it uses tags, because eventually I think it would be nice to switch out with something else like data from another source (like consul or etcd or something else). Because it might be tags or might be something else in the future, I was trying to come up with generic terms. 

Needle and haystack are very common terms in computer science. I'd love better suggestions for what to call the 'bucket and key' if anyone has any. Just saying those are bad isn't useful feedback for me to go make this better.

> On a more technical point of view, I think Resources in this context are not the best tools, as we want to do a search and get a list of node/IP. We need a function rather than a procedure. And to be honest, I'd rather not use Chef to get data/attributes from a search. A search for me should just return an IP/FQDN

Unfortunately, we have a few cases already where we do more than what you're describing, such as looking for redis attribute data on other nodes to setup sentinel or slaves, or looking for MySQL information on other nodes in mysql-multi to setup replication. The search for those data are pretty ugly right now, so I had things like that in mind for passing a block and using chef data.

Using a function instead of a procedure for those cases won't work (since they perform logic after returning search results, or don't simply return IP addresses). I tried to make a library that works for both use cases, simple and complex. I'm open to changing this to be a library that just wraps calls to `search()`, but I think we don't get much value in doing that. I think we're better off not using a library at all at that point.

> It seems we cannot really use other criteria like environment, or we would need something like :
> needle 'master AND chef_environment:#{node.chef_environment}'.

I'm not sure what you mean by "cannot use other criteria" just because criteria are a parameter you have to pass to the resource. You can use any criteria you want, but it's no easier or harder than passing it to this resource or to a chef search function. I thought about making the default for a 'needle' be the environment, but any search or any replacement for search would have to say `node.chef_environment` somewhere.

> node_ip = best_ip_for(discover('mysql','master'))

I was trying to give some verbose examples, but in the discovery resource, it could be as simple as:

```
discovery 'mysql' { needle 'master'; data &:best_ip_for }
```

> ps : I think it's better if we don't automatically fail on Chef::Solo. Otherwise it can be hard to test with ChefSpec (if we use the Solo provider). I've prefer to avoid to have to add a guard in my recipe.

There's actually a huge amount of unit testing in the PR, all using chefspec with Chef-Zero. I can remove the fail for chef-solo, but we do run the risk of someone converging it with chef-solo and just not noticing that search isn't working.

**Comment by jujugrrr** [comment]
> Just saying those are bad isn't useful feedback for me to go make this better.

I'm not saying it's bad, I'm saying it's confusing.

> Unfortunately, we have a few cases already where we do more than what you're describing, such as looking for redis attribute data on other nodes to setup sentinel or slaves

Indeed, still I'm wondering if we should do this. 

> Using a function instead of a procedure for those cases won't work (since they perform logic after returning search results, or don't simply return IP addresses)

Not sure to understand why a function would not allow logic as well. I think it is the same thing as above, 
Do we just except a value (IP endpoint), or do we except it to build attributes or create tags.

> I was trying to give some verbose examples, but in the discovery resource, it could be as simple as

:+1: 

> There's actually a huge amount of unit testing in the PR, all using chefspec with Chef-Zero. I can remove the fail for chef-solo, but we do run the risk of someone converging it with chef-solo and just not noticing that search isn't working.

Will it not return an error saying chef-solo doesn't support search anyway ? I'm just annoyed when I try to run Chefspec with the solo provisioner and a recipe decides it should fail the converge. It's just we have no way to by pass this but to use the Chef Zero provisioner. Anyway, no major issue on this one :wink:

**Comment by martinb3** [comment]
> > Just saying those are bad isn't useful feedback for me to go make this better.
> 
> I'm not saying it's bad, I'm saying it's confusing.

I guess what I'm asking is, what would you change to make it less confusing? :)

**Comment by prometheanfire** [comment]
search for tag:haystack if needle is defined AND tag:haystack is found, search for tag:haystack_needle as well.

**Comment by martinb3** [comment]
@prometheanfire -- 

> search for tag:haystack if needle is defined AND tag:haystack is found, search for tag:haystack_needle as well.

What about if we implement other backends? The goal was to make it independent of any particular backend, so ideally the concepts should be independent of the implementation.

**Comment by prometheanfire** [comment]
I'm not saying what backend we use

**Comment by prometheanfire** [comment]
search for haystack as an attribute of the node if needle is defined AND haystack is found as an attribute of the node, search for haystack_needle as well.

**Comment by prometheanfire** [comment]
search for haystack as an attribute of the node if needle is defined AND haystack is found as an attribute of the node, search for haystack_needle at the same time as well.

**Comment by prometheanfire** [comment]
Search for haystack as an attribute of the node.  If needle is defined AND haystack is found as an attribute of the node, search for haystack_needle at the same time as well.

**Comment by martinb3** [comment]
My proposed revision to the wording: 
"Nodes are assigned into groups called haystacks. Each node can also be assigned a particular piece of data, a needle, within that group. This resource allows you to search for nodes with the specific needle value in a given haystack. If no needle is given, it will find all nodes in that haystack."

**Comment by prometheanfire** [comment]
lgtm

**Comment by jujugrrr** [comment]
> My proposed revision to the wording

Sounds good! It's more comprehensible.

It seems a haystack or a needle is just a filter (based on tagging/group). In theory we should be able to search for a tag, or a combination of tags. Do we need to lock ourselves to haystack and needle(subgroup)?

I'm not familiar with other backends, but it seems for something like consul by example you can search on services then filter by tags.

Maybe needle should be an array and just accept tags. Haystack might be service.
We could name a haystack a service, and a needle a tag (and be able to give more than one), we could have an environment parameter as well, which default to the current node chef environment

**Comment by martinb3** [comment]
Hi all -- I've done another major revision. I think everyone will like this much better. Let me know what you think!

**Comment by prometheanfire** [comment]
I like it :+1:

**Comment by jujugrrr** [comment]
:+1:

**Pull request merged**
